<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cart</name>
   <tag></tag>
   <elementGuidId>80e83cf4-f294-4ded-9369-2fa52e8981be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.shopping_cart_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.shopping_cart_link</value>
      <webElementGuid>9f22f877-1f20-412a-827c-65e9a4082b57</webElementGuid>
   </webElementProperties>
</WebElementEntity>
